/** Local presentation documents. No content is generated by an external service. */
export const DEFAULT_DESIGN = Object.freeze({
  background: 'aurora', color: '#17394b', image: null, overlay: 25,
  panel: 'glass', accent: 'cyan', text: 'auto', font: 'sans',
  size: 'normal', radius: 'round',
});

export const LIMITS = Object.freeze({
  slides: 40, title: 160, subject: 100, slideTitle: 100, section: 60,
  body: 600, formula: 400, example: 250,
  imageBytes: 2 * 1024 * 1024, documentBytes: 8 * 1024 * 1024,
  inputImageBytes: 12 * 1024 * 1024,
});

const LESSON_TYPES = ['lecture', 'practice', 'seminar', 'lab', 'project'];
const DESIGN_OPTIONS = {
  background: ['aurora', 'paper', 'midnight', 'solid', 'image'],
  panel: ['glass', 'solid', 'none'], accent: ['cyan', 'blue', 'violet', 'green', 'amber'],
  text: ['auto', 'light', 'dark'], font: ['sans', 'serif'],
  size: ['normal', 'large'], radius: ['round', 'square'],
};
const isObject = (value) => !!value && typeof value === 'object' && !Array.isArray(value);
const copyDesign = (design) => Object.fromEntries(Object.keys(DEFAULT_DESIGN).map((key) => [
  key, isObject(design) && design[key] !== undefined ? design[key] : DEFAULT_DESIGN[key],
]));
const charCount = (value) => Array.from(value).length;

function normalizeSlide(slide, index) {
  const source = isObject(slide) ? slide : {};
  return {
    id: source.id === undefined ? `slide-${index + 1}` : source.id,
    title: source.title === undefined ? `Slayd ${index + 1}` : source.title,
    section: source.section === undefined ? 'Asosiy qism' : source.section,
    body: source.body === undefined ? '' : source.body,
    formula: source.formula === undefined ? '' : source.formula,
    example: source.example === undefined ? '' : source.example,
    image: source.image === undefined ? null : source.image,
    layout: source.layout === undefined ? (source.formula ? 'formula' : source.image ? 'image' : 'text') : source.layout,
    design: source.design == null ? null : copyDesign(source.design),
  };
}

/** An editable lesson outline, with at most five sections and no invented facts. */
export function makeSlides(count = 5, fields = {}) {
  const amount = Number.isFinite(Number(count)) ? Math.max(1, Math.min(LIMITS.slides, Math.floor(Number(count)))) : 5;
  const middle = fields.lesson_type === 'lab'
    ? ['Tajriba tartibi', 'Jihozlar va tajriba bosqichlarini yozing.']
    : fields.lesson_type === 'practice'
      ? ['Amaliy topshiriqlar', 'Topshiriq sharti va bajarish tartibini yozing.']
      : fields.lesson_type === 'seminar'
        ? ['Muhokama savollari', 'Muhokama savollari va asosiy dalillarni kiriting.']
        : fields.lesson_type === 'project'
          ? ['Loyiha bosqichlari', 'Loyiha vazifalari, bosqichlari va natijalarini yozing.']
          : ['Tahlil va misollar', 'Mavzuga mos misol va uning izohini kiriting.'];
  const allSections = [
    ['Kirish', 'Dars maqsadi va kutiladigan natijalarni yozing.'],
    ['Asosiy tushunchalar', 'Muhim tushunchalar va ta’riflarni kiriting.'],
    middle,
    ['Mustahkamlash', 'Bilimni tekshirish uchun savol yoki topshiriq kiriting.'],
    ['Xulosa', 'Asosiy xulosalar va keyingi vazifani yozing.'],
  ];
  const sections = amount >= 5 ? allSections : amount === 1 ? [allSections[0]] : [
    ...allSections.slice(0, amount - 1), allSections[4],
  ];
  const occurrences = {};
  return Array.from({ length: amount }, (_, index) => {
    const section = sections[Math.min(sections.length - 1, Math.floor(index * sections.length / amount))];
    occurrences[section[0]] = (occurrences[section[0]] || 0) + 1;
    const suffix = occurrences[section[0]] > 1 ? ` · ${occurrences[section[0]]}` : '';
    return normalizeSlide({
      title: index === 0 ? (fields.title || 'Yangi taqdimot') : `${section[0]}${suffix}`,
      section: section[0], body: section[1],
    }, index);
  });
}

export function makeProject(fields = {}) {
  const source = isObject(fields) ? fields : {};
  return {
    schema: 1, title: source.title === undefined ? 'Yangi taqdimot' : source.title,
    subject: source.subject === undefined ? '' : source.subject,
    lesson_type: source.lesson_type === undefined ? 'lecture' : source.lesson_type,
    design: copyDesign(source.design),
    slides: Array.isArray(source.slides)
      ? source.slides.map(normalizeSlide)
      : makeSlides(source.count === undefined ? 5 : source.count, source),
  };
}

/** Fill omitted editor fields without truncating or silently discarding oversized content. */
export function normalizeDocument(document) {
  if (!isObject(document)) return makeProject();
  const normalized = makeProject(document);
  if (document.schema !== undefined) normalized.schema = document.schema;
  // Retain a malformed slides value so validation can report it, rather than replace work.
  if (document.slides !== undefined && !Array.isArray(document.slides)) normalized.slides = document.slides;
  return normalized;
}

function dataUrlBytes(value) {
  if (typeof value !== 'string') return null;
  const match = /^data:image\/(png|jpeg);base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);
  if (!match || match[2].length % 4 !== 0) return null;
  const encoded = match[2];
  if (match[1] === 'png' && !encoded.startsWith('iVBORw0KGgo')) return null;
  if (match[1] === 'jpeg' && !encoded.startsWith('/9j/')) return null;
  return encoded.length / 4 * 3 - (encoded.endsWith('==') ? 2 : encoded.endsWith('=') ? 1 : 0);
}

/** Validate the same bounded fields that the server/exporter receives. */
export function validateDocument(document) {
  const errors = [];
  if (!isObject(document)) return ['Taqdimot ma’lumoti to‘g‘ri obyekt bo‘lishi kerak.'];
  const checkText = (value, max, label, required = false) => {
    if (typeof value !== 'string') errors.push(`${label}: matn kiriting.`);
    else if (required && !value.trim()) errors.push(`${label}: bo‘sh qoldirmang.`);
    else if (charCount(value) > max) errors.push(`${label}: ko‘pi bilan ${max} ta belgi kiriting.`);
  };
  const checkImage = (value, label) => {
    if (value == null) return;
    const bytes = dataUrlBytes(value);
    if (bytes == null) errors.push(`${label}: faqat PNG yoki JPEG rasmi qabul qilinadi.`);
    else if (bytes > LIMITS.imageBytes) errors.push(`${label}: rasm hajmi 2 MB dan oshmasin.`);
  };
  const checkDesign = (design, label) => {
    if (!isObject(design)) { errors.push(`${label}: dizayn sozlamalari noto‘g‘ri.`); return; }
    for (const [key, values] of Object.entries(DESIGN_OPTIONS)) {
      if (!values.includes(design[key])) errors.push(`${label}: “${key}” sozlamasi noto‘g‘ri.`);
    }
    if (typeof design.color !== 'string' || !/^#[0-9a-fA-F]{6}$/.test(design.color)) {
      errors.push(`${label}: rangni #17394b ko‘rinishida kiriting.`);
    }
    if (typeof design.overlay !== 'number' || !Number.isFinite(design.overlay) || design.overlay < 0 || design.overlay > 90) {
      errors.push(`${label}: fon xiraligi 0–90 oralig‘ida bo‘lsin.`);
    }
    checkImage(design.image, `${label}, fon rasmi`);
    if (design.background === 'image' && !design.image) errors.push(`${label}: orqa fon uchun rasm tanlang.`);
  };
  if (document.schema !== 1) errors.push('Taqdimot formati qo‘llab-quvvatlanmaydi.');
  checkText(document.title, LIMITS.title, 'Taqdimot nomi', true);
  checkText(document.subject, LIMITS.subject, 'Fan');
  if (!LESSON_TYPES.includes(document.lesson_type)) errors.push('Mashg‘ulot turini tanlang.');
  checkDesign(document.design, 'Umumiy dizayn');
  if (!Array.isArray(document.slides)) errors.push('Slaydlar ro‘yxati noto‘g‘ri.');
  else {
    if (!document.slides.length || document.slides.length > LIMITS.slides) errors.push('Taqdimotda 1–40 ta slayd bo‘lishi kerak.');
    const ids = new Set();
    document.slides.forEach((slide, index) => {
      const label = `${index + 1}-slayd`;
      if (!isObject(slide)) { errors.push(`${label}: slayd ma’lumoti noto‘g‘ri.`); return; }
      if (typeof slide.id !== 'string' || !slide.id.trim() || ids.has(slide.id)) errors.push(`${label}: slayd identifikatori takrorlangan yoki bo‘sh.`);
      ids.add(slide.id);
      checkText(slide.title, LIMITS.slideTitle, `${label}, sarlavha`, true);
      checkText(slide.section, LIMITS.section, `${label}, bo‘lim`);
      checkText(slide.body, LIMITS.body, `${label}, matn`);
      checkText(slide.formula, LIMITS.formula, `${label}, formula`);
      checkText(slide.example, LIMITS.example, `${label}, misol`);
      if (!['text', 'formula', 'image'].includes(slide.layout)) errors.push(`${label}: joylashuv turi noto‘g‘ri.`);
      checkImage(slide.image, `${label}, rasm`);
      if (slide.design != null) checkDesign(slide.design, `${label}, dizayn`);
    });
  }
  try {
    if (new TextEncoder().encode(JSON.stringify(document)).length > LIMITS.documentBytes) errors.push('Taqdimotning jami hajmi 8 MB dan oshmasin.');
  } catch { errors.push('Taqdimot ma’lumotini saqlash formatiga o‘girib bo‘lmadi.'); }
  return errors;
}

const TAG_FIELDS = {
  SLAYD: 'slide', SLIDE: 'slide', SARLAVHA: 'title', TITLE: 'title',
  BOLIM: 'section', SECTION: 'section', MATN: 'body', BODY: 'body',
  FORMULA: 'formula', MISOL: 'example', EXAMPLE: 'example',
};
const normalizeTag = (tag) => tag.toUpperCase().replace(/[‘’ʻʼ'`\s_-]/g, '');

function expandTaggedMarkup(text) {
  let inFormula = false;
  let openLatex = false;
  let openSlide = null;
  const expanded = text.replace(/\[(\/?)([A-Za-z0-9‘’ʻʼ'` _-]+)\]/g, (original, closing, rawName) => {
    const name = normalizeTag(rawName);
    const legacySlide = /^S(\d+)$/.exec(name);
    const legacyRow = /^(\d+)QATOR$/.exec(name);
    const field = name === 'LAT' ? 'formula' : TAG_FIELDS[name];
    if (!legacySlide && !legacyRow && !field) {
      if (inFormula) return original;
      throw new Error(`Noma’lum teg: ${original}. [SLAYD], [MATN] yoki [FORMULA] teglaridan foydalaning.`);
    }
    if (legacySlide) {
      if (openLatex) throw new Error('Formula uchun [/lat] yopish tegini kiriting.');
      inFormula = false;
      if (closing) {
        if (openSlide !== name) throw new Error(`${original}: ochilgan slayd tegiga mos kelmaydi.`);
        openSlide = null;
        return '\n---\n';
      }
      openSlide = name;
      return '\n[SLAYD] ';
    }
    if (legacyRow) {
      if (openLatex) throw new Error('Formula uchun [/lat] yopish tegini kiriting.');
      inFormula = false;
      return closing ? '\n[MATN] ' : `\n[${Number(legacyRow[1]) === 1 ? 'SARLAVHA' : 'MATN'}] `;
    }
    if (field === 'formula') {
      if (closing) {
        if (name === 'LAT' && !openLatex) throw new Error('[/lat] tegidan oldin [lat] tegini kiriting.');
        openLatex = false;
        inFormula = false;
        return '\n[MATN] ';
      }
      if (openLatex) throw new Error('Bitta slaydga bitta formula kiriting. Formulalarni alohida slaydlarga ajrating.');
      inFormula = true;
      openLatex = name === 'LAT';
      return '\n[FORMULA] ';
    }
    if (openLatex) throw new Error('Formula uchun [/lat] yopish tegini kiriting.');
    inFormula = false;
    if (closing) return field === 'slide' ? '\n---\n' : '\n[MATN] ';
    return `\n[${name}] `;
  });
  if (openLatex) throw new Error('Formula uchun [/lat] yopish tegini kiriting.');
  return expanded;
}

/**
 * [SLAYD] Title / [BO‘LIM] Section / [MATN] Text / [FORMULA] LaTeX / [MISOL] Text.
 * Tags may also use “MATN: text”. Markdown headings and --- start another slide.
 * Legacy [s1][1qator]Title[/1qator][2qator]Body[/2qator][lat]x^2[/lat][/s1]
 * uses row 1 as the title and later rows as body text. One formula per slide.
 * Plain text uses its first nonempty line as a title. Nothing is truncated.
 */
export function parseTaggedText(text) {
  if (typeof text !== 'string' || !text.trim()) return [];
  const slides = [];
  let current = null;
  let field = 'body';
  let formulaCount = 0;
  const start = (title = '') => { current = { title, section: '', body: '', formula: '', example: '' }; field = 'body'; formulaCount = 0; };
  const flush = () => {
    if (!current || !Object.values(current).some((value) => value.trim())) { current = null; return; }
    for (const key of Object.keys(current)) current[key] = current[key].trim();
    if (!current.title) current.title = `Slayd ${slides.length + 1}`;
    if (!current.section) current.section = 'Asosiy qism';
    slides.push(normalizeSlide(current, slides.length));
    current = null;
  };
  for (const line of expandTaggedMarkup(text.replace(/\r\n?/g, '\n')).split('\n')) {
    if (/^\s*---+\s*$/.test(line)) { flush(); field = 'body'; continue; }
    const heading = /^\s*#{1,2}\s+(.+?)\s*$/.exec(line);
    if (heading) { flush(); start(heading[1]); continue; }
    const tagMatch = /^\s*\[([^\]]+)\]\s*(.*)$/.exec(line)
      || /^\s*([A-Za-z‘’ʻʼ'` _-]+)\s*:\s*(.*)$/.exec(line);
    const tag = tagMatch ? TAG_FIELDS[normalizeTag(tagMatch[1])] : null;
    if (tag) {
      const value = tagMatch[2];
      if (tag === 'slide') { flush(); start(value); continue; }
      if (tag === 'title' && current?.title) flush();
      if (!current) start();
      if (tag === 'formula' && ++formulaCount > 1) throw new Error('Bitta slaydga bitta formula kiriting. Formulalarni alohida slaydlarga ajrating.');
      field = tag;
      current[field] += `${current[field] ? '\n' : ''}${value}`;
      continue;
    }
    if (!current) {
      if (!line.trim()) continue;
      start(line.trim());
    } else current[field] += `${current[field] ? '\n' : ''}${line}`;
  }
  flush();
  return slides;
}

export function sampleProject() {
  return makeProject({
    title: 'To‘rt fan: formulalar bilan ishlash', subject: 'Matematika, fizika, kimyo, biologiya',
    slides: [
      { title: 'Matematika: kvadrat tenglama', section: 'Matematika', body: 'Kvadrat tenglama ildizlarini topish formulasi. a nolga teng bo‘lmasligi kerak; haqiqiy ildizlar uchun diskriminant manfiy emas.', formula: 'x_{1,2}=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}', example: 'Ko‘paytuvchilarga ajraladigan misol: x kvadrat minus 5x plus 6. Ildizlari 2 va 3.' },
      { title: 'Fizika: butun olam tortishish qonuni', section: 'Fizika', body: 'Ikki nuqtaviy jismning tortishish kuchi massalar ko‘paytmasiga to‘g‘ri, ular orasidagi masofa kvadratiga teskari proporsional. G — gravitatsion doimiy.', formula: 'F=G\\frac{m_1m_2}{r^2}', example: 'Massalar o‘zgarmaganda masofa ikki baravar oshsa, tortishish kuchi to‘rt marta kamayadi.' },
      { title: 'Kimyo: eritmaning pH qiymati', section: 'Kimyo', body: 'Suyultirilgan eritmada pH vodorod ionlari konsentratsiyasining o‘nli logarifmi orqali taxminan hisoblanadi. Konsentratsiya mol/L da ifodalanadi.', formula: '\\mathrm{pH}\\approx-\\log_{10}\\left(\\frac{[\\mathrm{H}^{+}]}{1\\,\\mathrm{mol/L}}\\right)', example: 'Vodorod ionlari konsentratsiyasi litriga 0,001 mol bo‘lsa, pH taxminan 3 ga teng.' },
      { title: 'Biologiya: Hardy–Weinberg tenglamasi', section: 'Biologiya', body: 'Muvozanatdagi populyatsiyada ikki allel chastotalari p va q bo‘lib, p + q = 1. Genotip chastotalari shu allel chastotalari orqali hisoblanadi.', formula: 'p^2+2pq+q^2=1', example: 'p = 0,6 va q = 0,4 bo‘lsa, genotip chastotalari: 0,36; 0,48; 0,16.' },
    ],
  });
}

function imageDimensions(bytes, type) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (type === 'image/png') {
    if (bytes.length < 24 || ![137, 80, 78, 71, 13, 10, 26, 10].every((value, index) => bytes[index] === value)
      || view.getUint32(8) !== 13 || String.fromCharCode(...bytes.subarray(12, 16)) !== 'IHDR') throw new Error('PNG rasmi buzilgan yoki formati noto‘g‘ri.');
    return [view.getUint32(16), view.getUint32(20)];
  }
  if (bytes.length < 4 || bytes[0] !== 255 || bytes[1] !== 216 || bytes[2] !== 255) throw new Error('JPEG rasmi buzilgan yoki formati noto‘g‘ri.');
  let position = 2;
  const frameMarkers = new Set([0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce, 0xcf]);
  while (position + 3 < bytes.length) {
    if (bytes[position++] !== 255) break;
    while (position < bytes.length && bytes[position] === 255) position++;
    const marker = bytes[position++];
    if (marker === 0xd9 || marker === 0xda) break;
    if (marker === 0x01 || (marker >= 0xd0 && marker <= 0xd8)) continue;
    if (position + 2 > bytes.length) break;
    const length = view.getUint16(position);
    if (length < 2 || position + length > bytes.length) break;
    if (frameMarkers.has(marker)) {
      if (length < 8) break;
      return [view.getUint16(position + 5), view.getUint16(position + 3)];
    }
    position += length;
  }
  throw new Error('JPEG rasmining o‘lchamini aniqlab bo‘lmadi.');
}

async function decodeImage(file) {
  if (typeof createImageBitmap === 'function') {
    const bitmap = await createImageBitmap(file);
    return { source: bitmap, release: () => bitmap.close() };
  }
  const url = URL.createObjectURL(file);
  try {
    const source = await new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => reject(new Error('Rasmni ochib bo‘lmadi. Boshqa PNG yoki JPEG rasm tanlang.'));
      img.src = url;
    });
    return { source, release: () => URL.revokeObjectURL(url) };
  } catch (error) { URL.revokeObjectURL(url); throw error; }
}

/** Decode, bound, and locally resize user image files; resolves to a PNG/JPEG data URL. */
export async function normalizeImage(file) {
  if (!file || !['image/png', 'image/jpeg'].includes(file.type)) throw new Error('Faqat PNG yoki JPEG rasm tanlang.');
  if (!Number.isFinite(file.size) || file.size <= 0) throw new Error('Rasm fayli bo‘sh yoki noto‘g‘ri.');
  if (file.size > LIMITS.inputImageBytes) throw new Error('Tanlangan rasm 12 MB dan katta. Kichikroq rasm tanlang.');
  const bytes = new Uint8Array(await file.arrayBuffer());
  if (bytes.byteLength > LIMITS.inputImageBytes) throw new Error('Tanlangan rasm 12 MB dan katta. Kichikroq rasm tanlang.');
  const [headerWidth, headerHeight] = imageDimensions(bytes, file.type);
  if (!headerWidth || !headerHeight || headerWidth > 16384 || headerHeight > 16384 || headerWidth * headerHeight > 40000000) {
    throw new Error('Rasm o‘lchami juda katta. 40 megapikseldan kichikroq rasm tanlang.');
  }
  if (typeof document === 'undefined' || typeof document.createElement !== 'function') throw new Error('Rasmni tayyorlash uchun brauzerdan foydalaning.');
  let decoded;
  let canvas;
  try {
    decoded = await decodeImage(file);
    const width = decoded.source.naturalWidth || decoded.source.width;
    const height = decoded.source.naturalHeight || decoded.source.height;
    if (!width || !height || width > 16384 || height > 16384 || width * height > 40000000) throw new Error('Rasm o‘lchami juda katta yoki noto‘g‘ri.');
    canvas = document.createElement('canvas');
    const context = canvas.getContext('2d');
    if (!context) throw new Error('Brauzerda rasmni tayyorlab bo‘lmadi.');
    let ratio = Math.min(1, 1600 / Math.max(width, height));
    for (let attempt = 0; attempt < 9; attempt++) {
      canvas.width = Math.max(1, Math.round(width * ratio));
      canvas.height = Math.max(1, Math.round(height * ratio));
      context.clearRect(0, 0, canvas.width, canvas.height);
      if (file.type === 'image/jpeg') {
        context.fillStyle = '#ffffff';
        context.fillRect(0, 0, canvas.width, canvas.height);
      }
      context.drawImage(decoded.source, 0, 0, canvas.width, canvas.height);
      // PNG keeps transparency; JPEG quality is reduced before further resizing.
      for (const quality of file.type === 'image/jpeg' ? [0.9, 0.82, 0.72, 0.62] : [undefined]) {
        const result = canvas.toDataURL(file.type, quality);
        const resultBytes = dataUrlBytes(result);
        if (resultBytes != null && resultBytes <= LIMITS.imageBytes) return result;
      }
      ratio *= 0.75;
    }
    throw new Error('Rasmni 2 MB gacha kichraytirib bo‘lmadi. Boshqa rasm tanlang.');
  } catch (error) {
    if (error instanceof Error && /[‘’]|PNG|JPEG|MB|Brauzer/.test(error.message)) throw error;
    throw new Error('Rasmni ochib bo‘lmadi. Boshqa PNG yoki JPEG rasm tanlang.');
  } finally {
    decoded?.release();
    if (canvas) { canvas.width = 1; canvas.height = 1; }
  }
}

export function formatTime(value) {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '—';
  return new Intl.DateTimeFormat('uz-UZ', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(date);
}
