// REV110: dars boshidagi va suhbatdagi iboralar 10 tilda (bog'cha kitoblari tarjimasidan avtomatik olingan).
export const OCHILISH_LUGAT = {
 "en": {
  "hello": "Hello!",
  "morning": "Good morning!",
  "how": "How are you?",
  "fine": "I'm fine, thank you!",
  "weather": "What's the weather like?",
  "sunny": "It's sunny.",
  "cloudy": "It's cloudy.",
  "rainy": "It's rainy.",
  "snowy": "It's snowy.",
  "cold": "It's cold.",
  "hot": "It's hot.",
  "remember": "Do you remember?",
  "what": "What is it?",
  "welldone": "Well done!",
  "go": "Let's go!",
  "look": "Look!",
  "fine2": "I'm fine!",
  "happy": "I'm happy!",
  "name": "What's your name?",
  "myname": "My name is…",
  "old": "How old are you?",
  "five": "I am five.",
  "six": "I am six.",
  "seven": "I am seven.",
  "likeapples": "Do you like apples?",
  "yesdo": "Yes, I do.",
  "nodont": "No, I don't.",
  "canswim": "Can you swim?",
  "yescan": "Yes, I can.",
  "nocan": "No, I can't.",
  "yes": "Yes!"
 },
 "ru": {
  "hello": "Привет!",
  "morning": "Доброе утро!",
  "how": "Как дела?",
  "fine": "Хорошо, спасибо!",
  "weather": "Какая погода?",
  "sunny": "Солнечно.",
  "cloudy": "Облачно.",
  "rainy": "Идёт дождь.",
  "snowy": "Идёт снег.",
  "cold": "Холодно.",
  "hot": "Жарко.",
  "remember": "Помнишь?",
  "what": "Что это?",
  "welldone": "Молодец!",
  "go": "Пойдём!",
  "look": "Смотри!",
  "fine2": "Хорошо!",
  "happy": "Я рад!",
  "name": "Как тебя зовут?",
  "myname": "Меня зовут…",
  "old": "Сколько тебе лет?",
  "five": "Мне пять лет.",
  "six": "Мне шесть лет.",
  "seven": "Мне семь лет.",
  "likeapples": "Ты любишь яблоки?",
  "yesdo": "Да, люблю.",
  "nodont": "Нет, не люблю.",
  "canswim": "Ты умеешь плавать?",
  "yescan": "Да, умею.",
  "nocan": "Нет, не умею.",
  "yes": "Да!"
 },
 "ar": {
  "hello": "مَرْحَبًا!",
  "morning": "صَبَاحُ الْخَيْر!",
  "how": "كَيْفَ حَالُك؟",
  "fine": "أَنَا بِخَيْر، شُكْرًا!",
  "weather": "كَيْفَ الْجَوّ؟",
  "sunny": "الْجَوُّ مُشْمِس.",
  "cloudy": "الْجَوُّ غَائِم.",
  "rainy": "الْجَوُّ مُمْطِر.",
  "snowy": "الثَّلْجُ يَتَسَاقَط.",
  "cold": "الْجَوُّ بَارِد.",
  "hot": "الْجَوُّ حَارّ.",
  "remember": "هَلْ تَتَذَكَّر؟",
  "what": "مَا هٰذَا؟",
  "welldone": "أَحْسَنْت!",
  "go": "هَيَّا بِنَا!",
  "look": "اُنْظُرْ!",
  "fine2": "أَنَا بِخَيْر!",
  "happy": "أَنَا سَعِيد!",
  "name": "مَا اسْمُك؟",
  "myname": "اِسْمِي…",
  "old": "كَمْ عُمْرُك؟",
  "five": "عُمْرِي خَمْسُ سَنَوَات.",
  "six": "عُمْرِي سِتُّ سَنَوَات.",
  "seven": "عُمْرِي سَبْعُ سَنَوَات.",
  "likeapples": "هَلْ تُحِبُّ التُّفَّاح؟",
  "yesdo": "نَعَم، أُحِبُّه.",
  "nodont": "لَا، لَا أُحِبُّه.",
  "canswim": "هَلْ تَسْتَطِيعُ أَنْ تَسْبَح؟",
  "yescan": "نَعَم، أَسْتَطِيع.",
  "nocan": "لَا، لَا أَسْتَطِيع.",
  "yes": "نَعَم!"
 },
 "tr": {
  "hello": "Merhaba!",
  "morning": "Günaydın!",
  "how": "Nasılsın?",
  "fine": "İyiyim, teşekkür ederim!",
  "weather": "Hava nasıl?",
  "sunny": "Hava güneşli.",
  "cloudy": "Hava bulutlu.",
  "rainy": "Hava yağmurlu.",
  "snowy": "Hava karlı.",
  "cold": "Hava soğuk.",
  "hot": "Hava sıcak.",
  "remember": "Hatırlıyor musun?",
  "what": "Bu ne?",
  "welldone": "Aferin!",
  "go": "Hadi gidelim!",
  "look": "Bak!",
  "fine2": "İyiyim!",
  "happy": "Mutluyum!",
  "name": "Adın ne?",
  "myname": "Benim adım…",
  "old": "Kaç yaşındasın?",
  "five": "Beş yaşındayım.",
  "six": "Altı yaşındayım.",
  "seven": "Yedi yaşındayım.",
  "likeapples": "Elma sever misin?",
  "yesdo": "Evet, severim.",
  "nodont": "Hayır, sevmem.",
  "canswim": "Yüzebilir misin?",
  "yescan": "Evet, yapabilirim.",
  "nocan": "Hayır, yapamam.",
  "yes": "Evet!"
 },
 "de": {
  "hello": "Hallo!",
  "morning": "Guten Morgen!",
  "how": "Wie geht es dir?",
  "fine": "Mir geht es gut, danke!",
  "weather": "Wie ist das Wetter?",
  "sunny": "Es ist sonnig.",
  "cloudy": "Es ist bewölkt.",
  "rainy": "Es regnet.",
  "snowy": "Es schneit.",
  "cold": "Es ist kalt.",
  "hot": "Es ist heiß.",
  "remember": "Weißt du es noch?",
  "what": "Was ist das?",
  "welldone": "Gut gemacht!",
  "go": "Los geht's!",
  "look": "Schau!",
  "fine2": "Mir geht es gut!",
  "happy": "Ich bin fröhlich!",
  "name": "Wie heißt du?",
  "myname": "Ich heiße …",
  "old": "Wie alt bist du?",
  "five": "Ich bin fünf.",
  "six": "Ich bin sechs.",
  "seven": "Ich bin sieben.",
  "likeapples": "Magst du Äpfel?",
  "yesdo": "Ja, mag ich.",
  "nodont": "Nein, mag ich nicht.",
  "canswim": "Kannst du schwimmen?",
  "yescan": "Ja, das kann ich.",
  "nocan": "Nein, das kann ich nicht.",
  "yes": "Ja!"
 },
 "fr": {
  "hello": "Bonjour !",
  "morning": "Bonjour !",
  "how": "Comment ça va ?",
  "fine": "Ça va bien, merci !",
  "weather": "Quel temps fait-il ?",
  "sunny": "Il y a du soleil.",
  "cloudy": "C'est nuageux.",
  "rainy": "Il pleut.",
  "snowy": "Il neige.",
  "cold": "Il fait froid.",
  "hot": "Il fait chaud.",
  "remember": "Tu te souviens ?",
  "what": "Qu'est-ce que c'est ?",
  "welldone": "Bravo !",
  "go": "On y va !",
  "look": "Regarde !",
  "fine2": "Ça va bien !",
  "happy": "Je suis content !",
  "name": "Comment tu t'appelles ?",
  "myname": "Je m'appelle…",
  "old": "Tu as quel âge ?",
  "five": "J'ai cinq ans.",
  "six": "J'ai six ans.",
  "seven": "J'ai sept ans.",
  "likeapples": "Tu aimes les pommes ?",
  "yesdo": "Oui, j'aime.",
  "nodont": "Non, je n'aime pas.",
  "canswim": "Tu sais nager ?",
  "yescan": "Oui, je sais.",
  "nocan": "Non, je ne sais pas.",
  "yes": "Oui !"
 },
 "es": {
  "hello": "¡Hola!",
  "morning": "¡Buenos días!",
  "how": "¿Cómo estás?",
  "fine": "¡Estoy bien, gracias!",
  "weather": "¿Qué tiempo hace?",
  "sunny": "Hace sol.",
  "cloudy": "Está nublado.",
  "rainy": "Llueve.",
  "snowy": "Nieva.",
  "cold": "Hace frío.",
  "hot": "Hace calor.",
  "remember": "¿Te acuerdas?",
  "what": "¿Qué es?",
  "welldone": "¡Muy bien!",
  "go": "¡Vamos!",
  "look": "¡Mira!",
  "fine2": "¡Estoy bien!",
  "happy": "¡Estoy contento!",
  "name": "¿Cómo te llamas?",
  "myname": "Me llamo…",
  "old": "¿Cuántos años tienes?",
  "five": "Tengo cinco años.",
  "six": "Tengo seis años.",
  "seven": "Tengo siete años.",
  "likeapples": "¿Te gustan las manzanas?",
  "yesdo": "Sí, me gusta.",
  "nodont": "No, no me gusta.",
  "canswim": "¿Puedes nadar?",
  "yescan": "Sí, puedo.",
  "nocan": "No, no puedo.",
  "yes": "¡Sí!"
 },
 "ko": {
  "hello": "안녕하세요!",
  "morning": "좋은 아침이에요!",
  "how": "잘 지내?",
  "fine": "잘 지내요, 고마워요!",
  "weather": "날씨가 어때요?",
  "sunny": "해가 쨍쨍해요.",
  "cloudy": "흐려요.",
  "rainy": "비가 와요.",
  "snowy": "눈이 와요.",
  "cold": "추워요.",
  "hot": "더워요.",
  "remember": "기억나요?",
  "what": "이게 뭐예요?",
  "welldone": "잘했어요!",
  "go": "가자!",
  "look": "봐!",
  "fine2": "잘 지내요!",
  "happy": "기뻐요!",
  "name": "이름이 뭐야?",
  "myname": "내 이름은…",
  "old": "몇 살이야?",
  "five": "나는 다섯 살이에요.",
  "six": "나는 여섯 살이에요.",
  "seven": "나는 일곱 살이에요.",
  "likeapples": "사과 좋아해?",
  "yesdo": "응, 좋아해.",
  "nodont": "아니, 안 좋아해.",
  "canswim": "수영할 수 있어?",
  "yescan": "응, 할 수 있어.",
  "nocan": "아니, 못 해.",
  "yes": "네!"
 },
 "ja": {
  "hello": "こんにちは！",
  "morning": "おはよう！",
  "how": "げんき？",
  "fine": "げんきだよ、ありがとう！",
  "weather": "どんな おてんき？",
  "sunny": "はれだよ。",
  "cloudy": "くもりだよ。",
  "rainy": "あめだよ。",
  "snowy": "ゆきだよ。",
  "cold": "さむいよ。",
  "hot": "あついよ。",
  "remember": "おぼえて いるかな？",
  "what": "これは なに？",
  "welldone": "よく できました！",
  "go": "いこう！",
  "look": "みて！",
  "fine2": "げんきだよ！",
  "happy": "うれしい！",
  "name": "おなまえは？",
  "myname": "わたしの なまえは…",
  "old": "なんさい？",
  "five": "ごさいです。",
  "six": "ろくさいです。",
  "seven": "ななさいです。",
  "likeapples": "りんごは すき？",
  "yesdo": "うん、すき。",
  "nodont": "ううん、すきじゃない。",
  "canswim": "およげる？",
  "yescan": "うん、できるよ。",
  "nocan": "ううん、できない。",
  "yes": "うん！"
 },
 "zh": {
  "hello": "你好！",
  "morning": "早上好！",
  "how": "你好吗？",
  "fine": "我很好，谢谢！",
  "weather": "天气怎么样？",
  "sunny": "今天是晴天。",
  "cloudy": "今天多云。",
  "rainy": "下雨了。",
  "snowy": "下雪了。",
  "cold": "天气很冷。",
  "hot": "天气很热。",
  "remember": "你还记得吗？",
  "what": "这是什么？",
  "welldone": "真棒！",
  "go": "我们走吧！",
  "look": "看！",
  "fine2": "我很好！",
  "happy": "我很开心！",
  "name": "你叫什么名字？",
  "myname": "我叫……",
  "old": "你几岁了？",
  "five": "我五岁。",
  "six": "我六岁。",
  "seven": "我七岁。",
  "likeapples": "你喜欢苹果吗？",
  "yesdo": "是的，我喜欢。",
  "nodont": "不，我不喜欢。",
  "canswim": "你会游泳吗？",
  "yescan": "是的，我会。",
  "nocan": "不，我不会。",
  "yes": "是的！"
 }
};
